// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: refresh_tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (refresh_token, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING refresh_token, created_at, updated_at, user_id, expires_at, revoked_at
`

type CreateRefreshTokenParams struct {
	RefreshToken string
	UserID       uuid.UUID
	ExpiresAt    time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.RefreshToken, arg.UserID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const findRefreshToken = `-- name: FindRefreshToken :one
SELECT refresh_token, created_at, updated_at, user_id, expires_at, revoked_at FROM refresh_tokens
WHERE refresh_token = $1
`

func (q *Queries) FindRefreshToken(ctx context.Context, refreshToken string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, findRefreshToken, refreshToken)
	var i RefreshToken
	err := row.Scan(
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :one
UPDATE refresh_tokens
SET updated_at = NOW(), revoked_at = NOW()
WHERE refresh_token = $1
RETURNING refresh_token, created_at, updated_at, user_id, expires_at, revoked_at
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, refreshToken string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, revokeRefreshToken, refreshToken)
	var i RefreshToken
	err := row.Scan(
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
